"""Add Gita models

Revision ID: 15797052256f
Revises: 263cdb0fc7b4
Create Date: 2026-09-12 17:23:05.333095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15797052256f'
down_revision: Union[str, Sequence[str], None] = '263cdb0fc7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gita_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title_sanskrit', sa.String(), nullable=False),
    sa.Column('title_transliteration', sa.String(), nullable=False),
    sa.Column('title_english', sa.String(), nullable=False),
    sa.Column('title_hindi', sa.String(), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=False),
    sa.Column('summary_hi', sa.Text(), nullable=True),
    sa.Column('total_verses', sa.Integer(), nullable=False),
    sa.Column('themes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gita_chapters_chapter_number'), 'gita_chapters', ['chapter_number'], unique=True)
    op.create_index(op.f('ix_gita_chapters_id'), 'gita_chapters', ['id'], unique=False)
    op.create_table('gita_verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('verse_number', sa.Integer(), nullable=False),
    sa.Column('verse_key', sa.String(), nullable=False),
    sa.Column('sanskrit', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=False),
    sa.Column('translation_en', sa.Text(), nullable=False),
    sa.Column('translation_hi', sa.Text(), nullable=True),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('explanation_hi', sa.Text(), nullable=True),
    sa.Column('context_en', sa.Text(), nullable=True),
    sa.Column('context_hi', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('concepts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('emotions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('life_situations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('source_license', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['gita_chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gita_verses_chapter_number'), 'gita_verses', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_gita_verses_concepts'), 'gita_verses', ['concepts'], unique=False)
    op.create_index(op.f('ix_gita_verses_id'), 'gita_verses', ['id'], unique=False)
    op.create_index(op.f('ix_gita_verses_keywords'), 'gita_verses', ['keywords'], unique=False)
    op.create_index(op.f('ix_gita_verses_topics'), 'gita_verses', ['topics'], unique=False)
    op.create_index(op.f('ix_gita_verses_verse_key'), 'gita_verses', ['verse_key'], unique=True)
    op.create_index(op.f('ix_gita_verses_verse_number'), 'gita_verses', ['verse_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gita_verses_verse_number'), table_name='gita_verses')
    op.drop_index(op.f('ix_gita_verses_verse_key'), table_name='gita_verses')
    op.drop_index(op.f('ix_gita_verses_topics'), table_name='gita_verses')
    op.drop_index(op.f('ix_gita_verses_keywords'), table_name='gita_verses')
    op.drop_index(op.f('ix_gita_verses_id'), table_name='gita_verses')
    op.drop_index(op.f('ix_gita_verses_concepts'), table_name='gita_verses')
    op.drop_index(op.f('ix_gita_verses_chapter_number'), table_name='gita_verses')
    op.drop_table('gita_verses')
    op.drop_index(op.f('ix_gita_chapters_id'), table_name='gita_chapters')
    op.drop_index(op.f('ix_gita_chapters_chapter_number'), table_name='gita_chapters')
    op.drop_table('gita_chapters')
    # ### end Alembic commands ###
