"""Add GitaEmbedding model

Revision ID: f55bdaf7ad36
Revises: 15797052256f
Create Date: 2026-09-12 18:15:26.354234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import pgvector

# revision identifiers, used by Alembic.
revision: str = 'f55bdaf7ad36'
down_revision: Union[str, Sequence[str], None] = '15797052256f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gita_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding_version', sa.String(), nullable=False),
    sa.Column('text_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verse_id'], ['gita_verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gita_embeddings_id'), 'gita_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_gita_embeddings_text_hash'), 'gita_embeddings', ['text_hash'], unique=False)
    op.create_index(op.f('ix_gita_embeddings_verse_id'), 'gita_embeddings', ['verse_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gita_embeddings_verse_id'), table_name='gita_embeddings')
    op.drop_index(op.f('ix_gita_embeddings_text_hash'), table_name='gita_embeddings')
    op.drop_index(op.f('ix_gita_embeddings_id'), table_name='gita_embeddings')
    op.drop_table('gita_embeddings')
    # ### end Alembic commands ###
